---
- name: Get letsencrypt certificate
  hosts: designate-in-a-box.23technologies.xyz
  gather_facts: false
  become: true

  vars:
    certbot_auto_renew: false
    certbot_create_if_missing: true
    certbot_create_method: standalone
    certbot_admin_email: acme@designate-in-a-box.23technologies.xyz
    certbot_create_standalone_stop_services: []
    certbot_create_command: >-
      {{ certbot_script }} certonly --standalone --noninteractive --agree-tos
      --email {{ cert_item.email | default(certbot_admin_email) }}
      --http-01-address 192.168.16.5
      -d {{ cert_item.domains | join(',') }}
      {{ '--pre-hook /etc/letsencrypt/renewal-hooks/pre/stop_services'
        if certbot_create_standalone_stop_services
      else '' }}
      {{ '--post-hook /etc/letsencrypt/renewal-hooks/post/start_services'
        if certbot_create_standalone_stop_services
      else '' }}

  roles:
    - geerlingguy.certbot

- name: Copy letsencrypt certificate
  hosts: designate-in-a-box.23technologies.xyz
  gather_facts: false

  tasks:
    - name: Prepare haproxy.pem certificate
      become: true
      shell: |
        cat /etc/letsencrypt/live/{{ kolla_internal_fqdn }}/privkey.pem \
            /etc/letsencrypt/live/{{ kolla_internal_fqdn }}/fullchain.pem \
            > /opt/configuration/environments/kolla/files/certificates/haproxy.pem

    - name: Copy haproxy.pem to haproxy-internal.pem
      become: true
      command: |
        cp /opt/configuration/environments/kolla/files/certificates/haproxy.pem \
           /opt/configuration/environments/kolla/files/certificates/haproxy-internal.pem
