---
- name: Create project
  hosts: localhost
  connection: local

  tasks:
    - name: "Create {{ openstack_project }} project"
      os_project:
        cloud: admin
        state: present
        name: "{{ openstack_project }}"
        domain_id: default

    - name: "Create {{ openstack_user }} user"
      os_user:
        cloud: admin
        state: present
        name: "{{ openstack_user }}"
        password: "{{ openstack_password }}"
        domain: default
        default_project: "{{ openstack_project }}"
      no_log: true

    - name: "Add member roles to user {{ openstack_user }}"
      os_user_role:
        cloud: admin
        state: present
        user: "{{ openstack_user }}"
        role: "{{ item }}"
        project: "{{ openstack_project }}"
      loop:
        - member
        - _member_
