---
name: Check terraform syntax

"on":
  push:
    paths:
      - 'terraform/**'
      - '.github/workflows/check-terraform-syntax.yml'
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/check-terraform.yml'

jobs:
  check-terraform-syntax:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform-version:
          - 1.0.0

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix.terraform-version }}
      - name: Terraform validate
        run: make validate
        working-directory: ./terraform
      - name: Terraform format
        run: terraform fmt -check
        working-directory: ./terraform
